FROM alpine
ENV TERM=xterm
RUN apk update && apk add vim
CMD [ "vim" ]

# 
# build docker image with:
# 		docker build -t dc_ex00 path/to/dockerfile
# 
# then start the dockerised image with:
# 		docker run -it --rm dc_ex00
# 
